cafe_project/cafe_app/urls.py
from django.urls import path, include
from . import views, api
from rest_framework import routers


app_name = 'cafe_app'

router = routers.DefaultRouter()
router.register('menu', api.MenuViewSet, 'meal_categories')
router.register('meals', api.MealViewSet, 'meals')
router.register('statistics_meals', api.TopMealViewSet, 'meals')
router.register('statistics_users', api.TopUserViewSet, 'users')
router.register('statistics_users_category/(?P<meal_category>[^/.]+)', api.TopUserCategoryViewSet, 'users')
router.register('statistics_chart/(?P<meal_id>[^/.]+)', api.MealStatisticsViewSet, 'clicks')
router.register('(?P<meal_category>[^/.]+)', api.MealCategoryViewSet, 'meals')


urlpatterns = [
    path('', views.menu, name='menu'),
    path('menu', views.menu, name='menu'),
    path('statistics', views.statistics, name='statistics'),
    path('category_statistics', views.category_statistics, name='category_statistics'),
    path('meal_statistics/<int:meal_id>', views.meal_statistics, name='meal_statistics'),
    path('<meal_category>', views.meal_category, name='meal_category'),
    path('<int:meal_id>/meal', views.meal, name='meal'),
    path('api/', include(router.urls)),
]

# urlpatterns += router.urls

cafe_project/cafe_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('cafe_app/', include('cafe_app.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe_project/cafe_app/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from .transliteration import transliteration


class Meal(models.Model):
    name = models.CharField('Название блюда', max_length=100)
    description = models.TextField('Описание блюда')
    price = models.IntegerField('Стоимость блюда')
    size = models.IntegerField('Граммовка блюда')

    class MealType(models.TextChoices):
        HOT_MEALS = 'Горячие блюда'
        DRINKS = 'Напитки'
        DESSERTS = 'Десерты'
        NO_TYPE = 'NO_TYPE'

    meal_type = models.CharField(
        'Категория блюда',
        max_length=30,
        choices=MealType.choices,
        default=MealType.NO_TYPE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name="Блюдо"
        verbose_name_plural="Блюда"
        ordering = ('meal_type', 'name')


class MealClick(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.DO_NOTHING)
    click_date = models.DateTimeField('Дата клика')
    user=models.ForeignKey(User, default=13, on_delete=models.DO_NOTHING)

def get_path_upload_image(file, meal):
    end_extention = file.split('.')[1]
    head = file.split('.')[0]
    if len(head) > 10:
        head = head[:10]
    file_name = head + '.' + end_extention
    return os.path.join('{}', '{}').format(meal, file_name)

class Photo(models.Model):
    meal = models.ForeignKey(Meal, verbose_name="Блюдо", related_name='photos', on_delete=models.CASCADE)
    image = models.ImageField("Фото", upload_to="meals/")

    def __str__(self):
        return '{}'.format(self.image.name)[15:]

    def save(self, *args, **kwargs):
        trans_meal = transliteration(self.meal)
        self.image.name = get_path_upload_image(self.image.name, trans_meal)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"
        ordering = ('id',)

cafe_project/cafe_app/views.py
from django.shortcuts import render
from django.db.models import OuterRef, Subquery, Count
from qsstats import QuerySetStats
from .models import Meal, User, MealClick
from django.utils import timezone


def menu(request):
    meal_categories = list(filter(lambda el: 'NO_TYPE' not in el[0], Meal.MealType.choices))
    return render(request, 'cafe_app/menu.html', {'meal_categories': meal_categories})


def meal_category(request, meal_category):
    meals_by_category = Meal.objects.filter(meal_type=meal_category)
    return render(request, 'cafe_app/meals.html', {'meals': meals_by_category, 'meal_category': meal_category})


def meal(request, meal_id):
    meal = Meal.objects.get(id=meal_id)
    meal.mealclick_set.create(click_date=timezone.now(), user=request.user)
    return render(request, 'cafe_app/meal.html', {'meal': meal})


def statistics(request):
    top3meals = Meal.objects.annotate(click_count=Count('mealclick')).order_by('-click_count')[:3]
    top10users = User.objects.annotate(user_click_count=Count('mealclick')).order_by('-user_click_count')[:10]
    meal_categories = list(filter(lambda el: 'NO_TYPE' not in el[0], Meal.MealType.choices))
    return render(request, 'cafe_app/statistics.html',
                  {'meals': top3meals, 'users': top10users, 'meal_categories': meal_categories})


def category_statistics(request):
    clicks = MealClick.objects.filter(meal__meal_type=request.GET.get('meal_category'), user=OuterRef("pk"))
    clicks_v = clicks.values('user')
    click_count = clicks_v.annotate(c=Count('*')).values('c')
    top_users = User.objects.filter(mealclick__in=clicks).distinct().annotate(
        user_click_count=Subquery(click_count)).order_by(
        '-user_click_count')[:int(request.GET.get('user_count'))]
    return render(request, 'cafe_app/category_statistics.html',
                  {'users': top_users, 'category': request.GET.get('meal_category'),
                   'num': request.GET.get('user_count')})


def meal_statistics(request, meal_id):
    meal = Meal.objects.get(id=meal_id)
    clicks = MealClick.objects.filter(meal=meal_id)
    interval = "days"
    num = 7
    if request.GET.get('num'):
        num = int(request.GET.get('num'))
    end_date = timezone.now()

    delta = timezone.timedelta(days=num)

    period_data = {"Часы": ("hours", timezone.timedelta(hours=num)),
                   "Дни": ("days", timezone.timedelta(days=num)),
                   "Недели": ("weeks", timezone.timedelta(weeks=num)),
                   "Месяцы": ("months", timezone.timedelta(days=num * 30))}
    if request.GET.get('period'):
        interval = period_data[request.GET.get('period')][0]
        delta = period_data[request.GET.get('period')][1]

    start_date = end_date - delta

    if interval == "hours":
        date_format = "M j G:i"
    else:
        date_format = "M j"

    qsstats = QuerySetStats(clicks, date_field='click_date', aggregate=Count('id'))
    stat_values = qsstats.time_series(start_date, end_date, interval=interval)

    print(qsstats)
    print(stat_values)

    return render(request, 'cafe_app/meal_statistics.html',
                  {'meal': meal, 'stat_values': stat_values, 'period_select': period_data.keys(),
                   'date_format': date_format})

cafe_project/templates/cafe_app/category_statistics.html
{% extends 'index.html' %}

{% block tittle %} Статистика по категории {{category}} {% endblock %}

{% block content %}
    {% if users %}
        <h1 style="color: #e12f5d">Топ {{num}} пользователей в категории "{{category}}"</h1>
            <table  style="border-style: double; font-size: 20px">
			    <thead style="border-style: double">
			    <tr>
				    <th style="border-right-style: double">Имя пользователя</th>
				    <th>Количество переходов</th>
			    </tr>
			    </thead>
			    <tbody>
				{% for user in users %}
                    <tr>
				        <td style="border-top-style: double; border-right-style: double">{{user.username}}</td>
				        <td style="border-top-style: double">{{user.user_click_count}}</td>
			        </tr>
                {% endfor %}
			    </tbody>
		    </table>
    {% else %}
        Недостаточно данных для формирования списка активных пользователей
    {% endif %}
{% endblock %}

cafe_project/templates/cafe_app/meal.html
{% extends 'index.html' %}

{% block tittle %} {{meal.name}} {% endblock %}

{% block content %}
    <h2>Характеристики блюда</h2>
    {% if meal %}
        <p><b>Блюдо: </b> {{meal.name}}</p>
        <p><b>Описание: </b> {{meal.description}}</p>
        <p><b>Цена: </b> {{meal.price}} BYN</p>
        <p><b>Размер: </b> {{meal.size}} г.</p>
    <h2><a style="color: #c7254e; text-decoration: none" href="{% url 'cafe_app:meal_statistics' meal.id %}">Статистика</a></h2>
    {% else %}
        Блюдо пустое :(
    {% endif %}
{% endblock %}

cafe_project/templates/cafe_app/meal_statistics.html
{% extends 'index.html' %}
{% load googlecharts %}

{% block tittle %} Статистика по блюду {{meal.name}} {% endblock %}

{% block content %}
    <h1 style="color: #7e4977">Статистика по блюду "{{meal.name}}"</h1>
    {% if stat_values %}
        <div id="count_graph"></div>
        {% googlecharts %}
	        {% data stat_values "count" %}
                {% col "string" "Дата" %}"{{ val|date:date_format }}"{% endcol %}
                {% col "number" "Число переходов" %}{{ val }}{% endcol %}
	        {% enddata %}

	        {% options %}
		        kind: "LineChart",
		        options: {
			        backgroundColor: "#f9f9f9",
			        colors: ["#e587d9"],
			        gridlineColor: "#ddd",
			        legend: "none",
                    vAxis: {minValue: 0, format: '#', title: "Число переходов", titleTextStyle: { fontSize: 20, color: "#7e4977" }},
			        chartArea: {left: 60, top: 20, bottom: 50, width: 1340, height: 500},
                    pointSize: 10,
			        width: 1400,
			        height: 600,
		        }
	        {% endoptions %}

	        {% graph "count_graph" "count" %}
        {% endgooglecharts %}

    {% else %}
        Необходимых данных нет :(
    {% endif %}
    <h3 style="color: #e12f5d">Здесь можно выбрать параметры статистического обзора</h3>
    <form action="{% url 'cafe_app:meal_statistics' meal.id %}">
        <label>
            Периодичность фиксации данных:
            <select name="period">
                {% for period in period_select %}
                    <option>{{period}}</option>
                {% endfor %}
<!--                <option>Часы</option>-->
<!--                <option>Дни</option>-->
<!--                <option>Недели</option>-->
<!--                <option>Месяцы</option>-->
            </select>
        </label><br/><br/>
        <label>
            Продолжительность периода:
            <input type="number" name="num">
        </label><br/><br/>
        <button type="submit">Посмотреть</button>
    </form>
{% endblock %}

cafe_project/templates/cafe_app/meals.html
{% extends 'index.html' %}

{% block tittle %} {{meal_category}} {% endblock %}

{% block content %}
    {% if meals %}
        <h1 style="color: #811833">{{meal_category}}:</h1>
        {% for meal in meals %}
            <h2><a href="{% url 'cafe_app:meal' meal.id %}">{{meal.name}}</a></h2>
        {% endfor %}
    {% else %}
        Пусто. Нет блюд в этой категории
    {% endif %}
{% endblock %}

cafe_project/templates/cafe_app/menu.html
{% extends 'index.html' %}

{% block tittle %} Меню {% endblock %}

{% block content %}
    {% if meal_categories %}
        <h1 style="color: #811833">Наше меню:</h1>
        {% for category in meal_categories %}
            <h2><a href="{% url 'cafe_app:meal_category' category.0 %}">{{category.0}}</a></h2>
        {% endfor %}
        <h2><a style="color: #c7254e; text-decoration: none" href="{% url 'cafe_app:statistics' %}">Общая статистика</a></h2>
    {% else %}
        Нет даже категорий блюд
    {% endif %}
{% endblock %}

cafe_project/templates/cafe_app/statistics.html
{% extends 'index.html' %}

{% block tittle %} Статистика {% endblock %}

{% block content %}
    {% if meals %}
        <h1 style="color: #e12f5d">Топ 3 наших блюда</h1>
        <table  style="border-style: double; font-size: 20px">
			<thead style="border-style: double">
			<tr>
				<th style="border-right-style: double">Название блюда</th>
				<th>Количество переходов</th>
			</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
                    <tr>
				        <td style="border-top-style: double; border-right-style: double">{{meal.name}}</td>
				        <td style="border-top-style: double">{{meal.click_count}}</td>
			        </tr>
                {% endfor %}
			</tbody>
		</table>
    {% else %}
        Недостаточно данных для формирования списка трех лидирующих блюд
    {% endif %}
    {% if users %}
        <h1 style="color: #e12f5d">Топ 10 активных пользователей</h1>
            <table  style="border-style: double; font-size: 20px">
			    <thead style="border-style: double">
			    <tr>
				    <th style="border-right-style: double">Имя пользователя</th>
				    <th>Количество переходов</th>
			    </tr>
			    </thead>
			    <tbody>
				{% for user in users %}
                    <tr>
				        <td style="border-top-style: double; border-right-style: double">{{user.username}}</td>
				        <td style="border-top-style: double">{{user.user_click_count}}</td>
			        </tr>
                {% endfor %}
			    </tbody>
		    </table>
    {% else %}
        Недостаточно данных для формирования списка десяти активных пользователей
    {% endif %}
    <h3 style="color: #e12f5d">Здесь можно посмотреть список наиболее активных пользователей в разрезе категорий блюд</h3>
    <form action="{% url 'cafe_app:category_statistics' %}">
        <label>
            Сколько пользователей вывести:
            <input type="number" name="user_count">
        </label><br/><br/>
        <label>
            Категория блюд:
            <select name="meal_category">
                {% for category in meal_categories %}
                    <option>{{category.0}}</option>
                {% endfor %}
            </select>
        </label><br/><br/>
        <button type="submit">Посмотреть</button>
    </form>
{% endblock %}

cafe_project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %} Наше любимое кафе {% endblock %}</title>
</head>
<body>
    {% block content %} Вы пришли в наше любимое кафе {% endblock %}
</body>
</html>